// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManualPeer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddManualPeer'](arg1, arg2, arg3);
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ClearTransferHistory() {
  return window['go']['main']['App']['ClearTransferHistory']();
}

export function GetActiveTasks() {
  return window['go']['main']['App']['GetActiveTasks']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetAuthToken() {
  return window['go']['main']['App']['GetAuthToken']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFailedCount() {
  return window['go']['main']['App']['GetFailedCount']();
}

export function GetFailedTasks() {
  return window['go']['main']['App']['GetFailedTasks']();
}

export function GetFolderContents(arg1) {
  return window['go']['main']['App']['GetFolderContents'](arg1);
}

export function GetLocalPeer() {
  return window['go']['main']['App']['GetLocalPeer']();
}

export function GetOnlinePeers() {
  return window['go']['main']['App']['GetOnlinePeers']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskCount() {
  return window['go']['main']['App']['GetTaskCount']();
}

export function GetTransferHistory() {
  return window['go']['main']['App']['GetTransferHistory']();
}

export function IsFolder(arg1) {
  return window['go']['main']['App']['IsFolder'](arg1);
}

export function PendingRestartFields() {
  return window['go']['main']['App']['PendingRestartFields']();
}

export function ProbePeer(arg1, arg2) {
  return window['go']['main']['App']['ProbePeer'](arg1, arg2);
}

export function RefreshPeers() {
  return window['go']['main']['App']['RefreshPeers']();
}

export function RemoteRestart(arg1) {
  return window['go']['main']['App']['RemoteRestart'](arg1);
}

export function RemoteShutdown(arg1) {
  return window['go']['main']['App']['RemoteShutdown'](arg1);
}

export function RemoveManualPeer(arg1) {
  return window['go']['main']['App']['RemoveManualPeer'](arg1);
}

export function ResumeFailedTransfers() {
  return window['go']['main']['App']['ResumeFailedTransfers']();
}

export function ResumeTransfer(arg1) {
  return window['go']['main']['App']['ResumeTransfer'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}

export function SendFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendFile'](arg1, arg2, arg3, arg4);
}

export function SendFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendFolder'](arg1, arg2, arg3, arg4);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}
