// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discovery} from '../models';
import {transfer} from '../models';
import {config} from '../models';
import {file} from '../models';

export function AddManualPeer(arg1:string,arg2:string,arg3:number):Promise<discovery.Peer>;

export function CancelTransfer(arg1:string):Promise<void>;

export function ClearTransferHistory():Promise<void>;

export function GetActiveTasks():Promise<Array<transfer.TransferTask>>;

export function GetAllTasks():Promise<Array<transfer.TransferTask>>;

export function GetAuthToken():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetFailedCount():Promise<number>;

export function GetFailedTasks():Promise<Array<transfer.TransferTask>>;

export function GetFolderContents(arg1:string):Promise<Array<file.FileInfo>>;

export function GetLocalPeer():Promise<discovery.Peer>;

export function GetOnlinePeers():Promise<Array<discovery.Peer>>;

export function GetPeers():Promise<Array<discovery.Peer>>;

export function GetTask(arg1:string):Promise<transfer.TransferTask>;

export function GetTaskCount():Promise<number>;

export function GetTransferHistory():Promise<Array<transfer.TransferTask>>;

export function IsFolder(arg1:string):Promise<boolean>;

export function PendingRestartFields():Promise<Array<string>>;

export function ProbePeer(arg1:string,arg2:number):Promise<void>;

export function RefreshPeers():Promise<Array<discovery.Peer>>;

export function RemoteRestart(arg1:string):Promise<void>;

export function RemoteShutdown(arg1:string):Promise<void>;

export function RemoveManualPeer(arg1:string):Promise<boolean>;

export function ResumeFailedTransfers():Promise<number>;

export function ResumeTransfer(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function SendFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SendFolder(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;
